## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
  file:
    directory: /etc/traefik/dynamic
    watch: true

# API and dashboard configuration
api:
  insecure: true


metrics:
  prometheus: {}

# pilot:
#  token: "this-pilot-id-is-burnt"
